name = "rubypets-frontend"
main = ".open-next/worker.js"
compatibility_date = "2025-12-08"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
