name = "rubypets-backend"
main = "backend/src/index.ts"
compatibility_date = "2025-12-08"
workers_dev = true
route = { pattern = "api.rubypets.com", custom_domain = true}

[vars]
ENVIRONMENT = "development"
R2_PUBLIC_BASE_URL = "https://media.rubypets.com"

[[d1_databases]]
binding = "DB"
database_name = "rubypets_dev"
database_id = "43b862e1-e59a-45ac-b9e3-78841a6f7696"
migrations_dir = "backend/migrations"

[[r2_buckets]]
binding = "R2_MEDIA"
bucket_name = "rubypets-media-dev"

[observability]
enabled = true
