name: rubypets_flutter
description: RubyPets mobile UI prototype with bottom navigation and stub pages
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
